name: mdos sandbox CI

on:
  push:
    branches: [ mdos ]
  pull_request:
    branches: [ mdos ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install and build webpack
      run: |
        npm install
        npm run build --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: webpack artifact
        path: public/

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-2016 ]
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with: 
        name: webpack artifact
        path: public/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: echo some shit
      run: |
        echo "Test output from docker stage"
    - name: Run docker hello-world
      run: |
        docker run -it hello-world

